version: '3'

services:
  jekyll:
    container_name: online-cv
    image: jekyll/jekyll:4.0
    command: jekyll serve --watch --force_polling --verbose --livereload --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 3.1 # Use the Ruby version compatible with GitHub Pages

  - name: Install dependencies
    run: bundle install

  - name: Build site
    run: bundle exec jekyll build